language: java
jdk: openjdk8

before_install:
  - chmod +x mvnw

install: true

script: ./mvnw clean package

cache:
  directories:
    - $HOME/.m2

before_deploy:
  - zip -r damoim *
  - mkdir -p deploy
  - mv damoim.zip deploy/damoim.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: damoim-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true