language: java
jdk: openjdk8

before_install:
  - chmod +x mvnw

script:
  - ./mvnw clean package
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

cache:
  directories:
    - $HOME/.m2

