spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://rdsdatabase.cwa8drqjuwbz.ap-northeast-2.rds.amazonaws.com:3306/damoim?verifyServerCertificate=false&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: damoim
    password: 1q2w3e

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  cache: redis
  redis:
    port: 6379
    host: 127.0.0.1

  data:
    redis:
      repositories:
        enabled: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  jwt:
    secret: DAMOIMJWTSECRET


cloud:
  aws:
    s3:
      bucket : jaehobucket
      dirName: damoim
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true


---




